### ISSUE TITLE
unable to save receive QR code(IOS)

### ISSUE THREAD

**Issue by MiaoShi09** [chaion/makkii#37]
unable to save receive QR code on iPhone.

**Comment by leoaion** [comment]
fixed in b67718d81829d5044c8afd75bd541bb454c06f4f

**Comment by MiaoShi09** [comment]
still not working. App crashed immediately when I clicked "save to my iphone"

**Comment by MiaoShi09** [comment]
passed
